# Basics
baseURL: https://ce.lna-dev.net
title: Common Extensions
enableGitInfo: true

# Modules
module:
  imports:
    - path: github.com/google/docsy
    - path: github.com/google/docsy/dependencies

# Content
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: tango

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango

params:
  links:
    user:
      - name: "GitHub"
        url: "https://github.com/LNA-DEV/CommonExtensions"
        icon: "fab fa-github"
      - name: "Impressum"
        url: "https://lna-dev.net/LegalDetails"
        icon: "fa fa-gavel"
  description: "Fachinformatiker Prüfungsvorbereitung ist eine Seite zur Prüfungsvorbereitung. Mit dieser Seite kannst du dich einfach auf die Fachinformatiker Prüfung vorbereiten."
  copyright: "The CommonExtension Authors"
  privacy_policy: "https://lna-dev.net/PrivacyPolicy/"
  ui:
    readingTime:
      enable: true

  offlineSearch: true
  algolia_docsearch: false
  offlineSearchSummaryLength: 70
  offlineSearchMaxResults: 10
  prism_syntax_highlighting: false

  # GitHub
  github_repo: "https://github.com/LNA-DEV/CommonExtensions"
  github_project_repo: "https://github.com/LNA-DEV/CommonExtensions"
  github_branch: "dev"

  mermaid:
    enable: false
    theme: default
  plantuml:
    enable: false
    theme: default
    svg_image_url: https://www.plantuml.com/plantuml/svg/
    svg: false
  katex:
    enable: false
    html_dom_element: document.body
    mhchem:
      enable: true
  print:
    disable_toc: false
  markmap:
    enable: false

# Language
languageCode: en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
contentDir: "content/en"
enableMissingTranslationPlaceholders: true

# Menu
menu:
  main:
    - name: GitHub
      weight: 50
      url: "https://github.com/LNA-DEV/FCommonExtensions"
      pre: <i class="fab fa-github"></i>

# Outputs
outputs:
  section:
    - HTML
    - RSS
    - print

# SEO
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

enableRobotsTXT: true
